/**
 * Created by wudan on 2017/8/7.
 */
module.exports = {
    SUCCESS: {code:'0',msg:'success'},

    CLIENT_ERROR: {code:'1000',msg:'client error.'},
    C_ADDRESS: {code:'1001', msg: 'Invalid parameter: address, it is not a valid jingtum address.'},
    C_SECRET: {code:'1002',msg:'Invalid parameter: secret.'},
    C_CURRENCY: {code:'1003', msg:'Invalid parameter: currency.'},
    C_ISSUER: {code:'1004',msg:'Invalid parameter: issuer.'},
    C_ORDER: {code:'1005', msg:'Invalid parameter: order, it is an object composed of four attributes: type, pair, amount and price.'},
    C_ORDER_TYPE: {code:'1006', msg:'Invalid parameter: order.type, it must be sell or buy'},
    C_ORDER_PRICE: {code:'1007', msg:'Invalid parameter: order.price, it is a number.'},
    C_ORDER_SEQ: {code:'1008', msg:'Invalid parameter: order sequence, it must be a number.'},
    C_HASH:{code:'1009',msg:'Invalid parameter: hash.'},
    C_NOT_ORDER:{code:'1010',msg:'not an order transaction.'},
    C_TX_ACCOUNT:{code:'1011',msg:'Transaction specified did not affect the given account.'},
    C_BASE:{code:'1012',msg:'Invalid parameter: base, it consists of two fields separated by \'+\' : [currency + counterparty].'},
    C_COUNTER:{code:'1013',msg:'Invalid parameter: counter, it consists of two fields separated by \'+\' : [currency + counterparty].'},
    C_ROUTER_DESTINATION:{code:'1014', msg:'Invalid parameter: destination_address, it is not a valid jingtum address.'},
    C_STR_AMOUNT:{code:'1015',msg:'Invalid parameter: amount, it is a string composed of three fields separated by \'+\': [value + currency + issuer], and currency can not be SWT.'},
    C_TYPE_PAYMENT:{code:'1016',msg:'Invalid payment type, it must be an object type.'},
    C_PAY_SOURCE:{code:'1017',msg:'Invalid parameter: payment.source, it is not a valid jingtum address.'},
    C_PAY_DESTINATION:{code:'1018',msg:'Invalid parameter: payment.destination, it is not a valid jingtum address.'},
    C_PAY_AMOUNT:{code:'1019',msg:'Invalid parameter: payment.amount, it is an object composed of three attributes: value, currency and issuer. And if the currency is SWT, the issuer must be empty string.'},
    C_PAY_MEMOS:{code:'1020',msg:'Invalid memos type, it must be an array.'},
    C_PAY_CHOICES:{code:'1021',msg:'Invalid choice type, it must be a string.'},
    C_PAY_CLIENT_ID:{code:'1022',msg:'Invalid client_id type, it must be a number.'},
    C_PAY_CLIENT_ID_EXITS:{code:'1023',msg:'Invalid parameter: client_id, already exits.'},
    C_PAY_NOT_EXITS_CHOICE:{code:'1024',msg:'Invalid parameter: choice, not exist.'},
    C_NOT_PAY:{code:'1025',msg:'not a payment transaction.'},
    C_ACCOUNT_NOT_FOUND:{code:'1026',msg:'Account not found.'},
    C_PAGE:{code:'1027',msg:'Invalid parameter:page, it is a positive integer.'},
    C_PER_PAGE:{code:'1028',msg:'Invalid parameter:results_per_page, it is a positive integer.'},
    C_ORDER_PAIR: {code:'1029', msg:'Invalid parameter: order.pair, it consists of two groups of currencies separated by \'/\'.'},
    C_ORDER_AMOUNT: {code:'1030', msg:'Invalid order.amount type, it is a number.'},
    C_MISSING_PARAMS : {code:'1031', msg:'Missing parameters'},
    C_Method: {code:'1032', msg:'Invalid parameter: method, it must be 0 or 1'},
    C_PAYLOAD: {code:'1033', msg:'Invalid parameter: payload, it must be string'},
    C_CONTRACT_AMOUNT:{code:'1034', msg:'Invalid parameter: amount,it must be a number greater than zero'},
    C_CONTRACT_PARAMS:{code:'1035', msg:'Invalid parameter: params,it must be an array'},
    C_BLOB:{code:'1036', msg:'Invalid parameter: blob, it must be a string'},
    C_PAY_MEMOS_TYPE:{code:'1037', msg:'Invalid parameter: memos, each item in the array must be a string'},
    C_MISSING_SECRET:{code:'1038', msg:'Missing parameter secret.'},
    C_MISSING_CLIENT_ID:{code:'1039', msg:'Missing parameter client_id.'},
    C_MISSING_PAYMENT:{code:'1040', msg:'Missing parameter payment.'},
    C_MISSING_PAYMENT_SOURCE:{code:'1041', msg:'Missing parameter payment.source.'},
    C_MISSING_PAYMENT_DES:{code:'1042', msg:'Missing parameter payment.destination.'},
    C_MISSING_PAYMENT_AMOUNT:{code:'1043', msg:'Missing parameter payment.amount.'},
    C_ORDER_PAIR_BASE:{code:'1044', msg:'Invalid parameter: order.pair, base consists of two fields separated by \':\' : [currency : issuer].'},
    C_ORDER_PAIR_COUNTER:{code:'1045', msg:'Invalid parameter: order.pair, counter consists of two fields separated by \':\' : [currency : issuer].'},
    C_ORDER_PAIR_CHECK:{code:'1046', msg:'Invalid parameter: order.pair, Notify developers to view log checking errors.'},
    C_CALL_DESTINATION:{code:'1047', msg:'Invalid parameter: destination, it is not a valid jingtum address.'},
    C_MARK_LIMIT:{code:'1048',msg:'The product of two numbers(results_per_page * page) must be an integer less than 300, page\'s  default value is 1.'},
    C_TYPE_RELATIONS:{code:'1049',msg:'Missing parameter:type, Choose from the following three types : trust, authorize or freeze.'},
    C_COUNTERPARTY:{code:'1050',msg:'Invalid parameter: counterparty, it is not a valid jingtum address.'},
    C_RELATION_AMOUNT:{code:'1051',msg:'Invalid parameter: relation amount, it is an object composed of three attributes: limit, currency and issuer. And if the currency is SWT, the issuer must be empty string.'},
    C_FREEZE_RELATIONS:{code:'1052',msg:'Invalid parameter: type, it must be unfreeze.'},
    C_MARKER_HASH:{code:'1053',msg:'Invalid parameter: marker.'},
    C_ORDERS_LIMIT:{code:'1054',msg:'The product of two numbers(results_per_page * page) must be an integer greater than 10, page\'s  default value is 1.'},
    C_TXS_LIMIT:{code:'1055',msg:'The product of two numbers(results_per_page * page) must be an integer less than 200, page\'s  default value is 1.'},
    C_ORDER_ISSUER:{code:'1056',msg:'Invalid parameter: issuer, It\'s a fixed value.'},
    C_ORDER_BOOK_BASE:{code:'1057',msg:'Invalid parameter: base, if the currency is SWT, the issuer must be empty string.'},
    C_ORDER_BOOK_COUNTER:{code:'1058',msg:'Invalid parameter: counter, if the currency is SWT, the issuer must be empty string.'},
    C_FORWARD: {code:'1059', msg:'Invalid parameter: forward.'},
    C_ERR_INVALID: {code:'1060', msg:'Invalid parameter: validated.'},
    C_FOO_TYPE: {code:'1061', msg:'Invalid parameter type: foo, it must be string.'},


    SERVER_ERROR: {code:'2000', msg:'server error'},

    TRANSACTION_ERROR: {code:'3000', msg:'transaction error'},
    T_WALLET:{code:'3001', msg:'Could not generate wallet'},
    T_ERR_GET_TX:{code:'3002',msg:'Get validated transaction error'},//支付获得同步结果时，查交易hash失败
    T_FAIL_GET_TX:{code:'3003',msg:'Enter into the account book failed'},//20s之后依然没有此交易信息，判定为写入区块链失败

    NETWORK_ERROR: {code: '4000', msg:'network error'},
    N_REMOTE: {code:'4001',msg: 'remote is disconnected'},
    N_TIMEOUT:{code:'4002', msg: 'time out!'},
    N_GATEWAY: {code:'4003', msg: 'bad gateway'}
};
